<a href="https://colab.research.google.com/github/Wait720/MH/blob/main/%D0%A8%D0%B5%D1%80%D1%81%D1%82%D1%8E%D0%BA_22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Створіть матрицю 3*3, заповнити її цілими випадковими числами від 1 до 5

In [6]:
import numpy as np

matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[2, 4, 1],
       [5, 1, 3],
       [5, 3, 3]])

2. Обчислити визначник матриці

In [7]:
det = np.linalg.det(matrix)
det

np.float64(-2.0)

3. Знайти добуток всіх елементів матриці

In [8]:
product = np.prod(matrix)
product

np.int64(5400)

In [10]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(5400)

4. Знайти суму всіх елементів матриці

In [11]:
sum = np.sum(matrix)
sum

np.int64(27)

5. Обчислити найбільший, найменший елементи

In [13]:
max_element = np.max(matrix)
print ("Найбільший елемент матриці це", max_element)
min_element = np.min(matrix)
print ("Найменший елемент матриці це", min_element)

Найбільший елемент матриці це 5
Найменший елемент матриці це 1


6. Знайти середнє значення елементів матриці

In [14]:
mean = np.mean (matrix)
print ("Середнє значення елементів матриці:", mean)

Середнє значення елементів матриці: 3.0


7. Знайти матрицю, що складена з квадратних коренів.

In [15]:
sqrt_matrix = np.sqrt(matrix)
print ("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[1.41421356 2.         1.        ]
 [2.23606798 1.         1.73205081]
 [2.23606798 1.73205081 1.73205081]]


8. Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [16]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
print ("Сума елементів кожного рядка:")
print(row_sums)

Сума елементів кожного рядка:
[[ 7]
 [ 9]
 [11]]


9. Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням.

In [20]:
vector = np.random.randint(0, 10, size=29)
print ("Початковий вектор:")
print(vector)
sorted_vector = np.sort(vector)[::-1]
print ("Вектор після сортування за спаданням:")
print (sorted_vector)

Початковий вектор:
[0 2 2 8 4 3 6 1 1 2 1 3 8 0 2 7 4 1 6 9 8 1 1 6 7 3 0 6 5]
Вектор після сортування за спаданням:
[9 8 8 8 7 7 6 6 6 6 5 4 4 3 3 3 2 2 2 2 1 1 1 1 1 1 0 0 0]


10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [21]:
from scipy import stats
mode = stats.mode (vector)
median = np.median (vector)
mean = np.mean (vector)
max_value = np.max(vector)
min_value = np.min(vector)
print ("Мода:", mode )
print ("Медіана:", median)
print ("Середнє:", mean)
print ("Максимальне значення:", max_value)
print ("Мінімальне значення:", min_value)

Мода: ModeResult(mode=np.int64(1), count=np.int64(6))
Медіана: 3.0
Середнє: 3.689655172413793
Максимальне значення: 9
Мінімальне значення: 0


11. Створити дві матриці 4*4, заповнені числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку.

In [43]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print ("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)

Матриця 1:
[[ 8  4  8  3]
 [ 5  5  8  6]
 [ 5  3 10  4]
 [ 9  3  9  2]]
Матриця 2:
[[1 1 9 5]
 [2 7 6 8]
 [2 2 5 6]
 [8 8 6 7]]


In [46]:
matrix_sum = matrix1 + matrix2
matrix_diff = matrix1 - matrix2
matrix_product = matrix1 * matrix2
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))
print ("Сума матриць:")
print(matrix_sum)
print ("Різниця матриць:")
print(matrix_diff)
print ("Поелементний добуток матриць:")
print (matrix_product)

Сума матриць:
[[ 9  5 17  8]
 [ 7 12 14 14]
 [ 7  5 15 10]
 [17 11 15  9]]
Різниця матриць:
[[ 7  3 -1 -2]
 [ 3 -2  2 -2]
 [ 3  1  5 -2]
 [ 1 -5  3 -5]]
Поелементний добуток матриць:
[[ 8  4 72 15]
 [10 35 48 48]
 [10  6 50 24]
 [72 24 54 14]]


*Висновок :* Лабораторна робота ознайомила з основами машинного навчання та практичним застосуванням елементів лінійної алгебри. Виконані завдання сприяли розумінню ключових концепцій та їх реалізації для вирішення практичних задач.

